variable "lb_arn" {}
variable "lb_target_arn" {}
variable "domain_name" {}
variable "domain_name1" {}
variable "domain_name2" {}
variable "prod_dns_name" {}
variable "prod_zone_id" {}
variable "stage_dns_name" {}
variable "stage_zone_id" {}
variable "domain_name3" {}
variable "prometheus_dns_name" {}
variable "prometheus_zone_id" {}
variable "domain_name4" {}
variable "grafana_dns_name" {}
variable "grafana_zone_id" {}
variable "domain_name5" {}