variable "ubuntu" {}
variable "instance_type" {}
variable "subnets" {}
variable "haproxy_sg" {}
variable "key_name" {}
variable "haproxymain" {}
variable "haproxybackup" {}
variable "master1" {}
variable "master2" {}
variable "master3" {}